export const projects = [
  {
    id: "brick",
    href: "/project/brick",
    year: 2024,
    name: "Brick",
    type: "Web Development",
    description:
      "Brick is my first simple eCommerce website with a responsive design, offering basic features such as product listings, a shopping cart, a simulated checkout process, and an intuitive user interface.",
    techs: ["React", "Redux", "Next.js", "Tailwind CSS", "Framer Motion"],
    mockup: "/images/projects/brick/mockup.png",
    thumbnail: "/images/projects/brick/thumbnail.png",
    images: [
      "/images/projects/brick/picture-1.png",
      "/images/projects/brick/picture-2.png",
      "/images/projects/brick/picture-3.png",
    ],
    repository: "https://github.com/lamtantai/brick-buy",
    liveDemo: "https://brick-buy.vercel.app/",
  },
  {
    id: "arcane",
    href: "/project/arcane",
    year: 2024,
    name: "Arcane",
    type: "Web Development",
    description:
      "Arcane 2 is a landing page for the TV series Arcane. The idea for this project came to me after seeing the announcement of Arcane's second season. The design for this project was inspired by the official website of Arcane.",
    techs: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    mockup: "/images/projects/arcane/mockup.png",
    thumbnail: "/images/projects/arcane/thumbnail.png",
    images: [
      "/images/projects/arcane/picture-1.png",
      "/images/projects/arcane/picture-2.png",
      "/images/projects/arcane/picture-3.png",
    ],
    achievements: [
      "Created a visually engaging and responsive layout inspired by the Arcane series.",
      "Learned the fundamentals of React and Framer Motion and applied them effectively in the project.",
    ],
    repository: "https://github.com/lamtantai/arcane",
    liveDemo: "https://arcane-landing-page.vercel.app/",
  },
  {
    id: "portfolio",
    href: "/project/portfolio",
    year: 2024,
    name: "Portfolio",
    type: "Web Development",
    description:
      "My portfolio showcases the web development projects I've built as a self-taught developer, focusing on coding for responsive websites, reflecting my dedication to learning and improving.",
    techs: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    mockup: "/images/projects/portfolio/mockup.png",
    thumbnail: "/images/projects/portfolio/thumbnail.png",
    images: [
      "/images/projects/portfolio/picture-1.png",
      "/images/projects/portfolio/picture-2.png",
      "/images/projects/portfolio/picture-3.png",
    ],
    repository: "https://github.com/lamtantai/tantai",
    liveDemo: "https://lamtai.vercel.app/",
  },
  {
    id: "mate",
    href: "/project/mate",
    year: 2024,
    name: "Mate",
    type: "Web Development",
    description:
      "Mate is the very first project I built when I started working on real-world projects. It allowed me to apply my self-taught skills in web development and gain hands-on experience in creating a functional and responsive website.",
    techs: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    mockup: "/images/projects/mate/mockup.png",
    thumbnail: "/images/projects/mate/thumbnail.png",
    images: [
      "/images/projects/mate/picture-1.png",
      "/images/projects/mate/picture-2.png",
      "/images/projects/mate/picture-3.png",
    ],
    repository: "https://github.com/lamtantai/yerba-mate",
    liveDemo: "https://matemeta.vercel.app/",
  },
];
